spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      database: Assembly
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
    template:
      queue: true
      exchange: ""
      routing-key: votingResult
    consumer:
      queue-name: votingResult
mongock:
  change-logs-scan-package:
    - br.com.assembly.dbchangelogs

server:
  servlet:
    context-path: /api